teams:
  - name: bots
    maintainers:
      - ryjones
    members:
      - lfdt-bot
  - name: lab-stewards
    maintainers:
      - tkuhrt
    members:
      - alvaropicazo
      - mbrandenburger
      - nidhi-singh02
  - name: security-managers
    maintainers:
      - ryjones
      - tkuhrt
    members:
      - hartm
  - name: paladin-admins
    maintainers:
      - jimthematrix
  - name: paladin-committers
    maintainers:
      - jimthematrix
    members:
      - EnriqueL8
      - awrichar
      - peterbroadhurst
      - Chengxuan
      - dwertent
      - hosie
      - gabriel-indik
      - SamMayWork
  - name: waterfall-committers
    maintainers:
      - ryjones
    members:
      - VladimirMezin
      - dimrogovoy
      - on-waterfall
repositories:
  - name: governance
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: LF-Decentralized-Trust-labs.github.io
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: paladin
    teams:
      bots: admin
      security-managers: read
      paladin-admins: admin
      paladin-committers: write
    visibility: public
  - name: waterfall-coordinator
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-gwat
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-one-click-setup-app
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
