teams:
- name: lab-stewards
  maintainers:
  - tkuhrt
  members:
  - alvaropicazo
  - mbrandenburger
  - nidhi-singh02
- name: security-managers
  maintainers:
  - hartm
  - ryjones
  - tkuhrt
repositories:
- name: governance
  teams:
    lab-stewards: maintain
    security-managers: read
  visibility: public
- name: LF-Decentralized-Trust-labs.github.io
  teams:
    lab-stewards: maintain
    security-managers: read
  visibility: public
