teams:
  - name: agora-glass-pumpkin-maintainers
    maintainers:
      - mikelodder7
  - name: agora-lab-admins
    maintainers:
      - mikelodder7
  - name: bots
    maintainers:
      - lfdt-bot
  - name: lab-stewards
    maintainers:
      - tkuhrt
    members:
      - alvaropicazo
      - mbrandenburger
      - nidhi-singh02
  - name: security-managers
    maintainers:
      - ryjones
      - tkuhrt
    members:
      - hartm
  - name: one-attestation-api-maintainers
    maintainers:
      - bvavala
  - name: paladin-admins
    maintainers:
      - jimthematrix
  - name: paladin-committers
    maintainers:
      - jimthematrix
    members:
      - EnriqueL8
      - awrichar
      - peterbroadhurst
      - Chengxuan
      - dwertent
      - hosie
      - gabriel-indik
      - SamMayWork
  - name: waterfall-committers
    maintainers:
      - ryjones
    members:
      - VladimirMezin
      - dimrogovoy
      - on-waterfall
  - name: web3db-committers
    maintainers:
      - tkuhrt
    members:
      - gpradofe
      - showkoth
      - IyNew
      - tjungND
repositories:
  - name: agora-allosaurus-rs
    teams:
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-bbs
    teams:
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-blsful
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-glass_pumpkin
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-key-share-proofs
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-unknown_order
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: agora-verifiable-encryption
    teams:
      agora-glass-pumpkin-maintainers: maintain
      agora-lab-admins: admin
      security-managers: read
    visibility: public
  - name: governance
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: LF-Decentralized-Trust-labs.github.io
    teams:
      bots: maintain
      lab-stewards: maintain
      security-managers: read
    visibility: public
  - name: one-attestation-api
    teams:
      bots: maintain
      lab-stewards: maintain
      one-attestation-api-maintainers: maintain
      security-managers: read
    visibility: public
  - name: paladin
    teams:
      bots: admin
      security-managers: read
      paladin-admins: admin
      paladin-committers: write
    visibility: public
  - name: waterfall-coordinator
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-gwat
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: waterfall-one-click-setup-app
    teams:
      bots: admin
      security-managers: read
      waterfall-committers: maintain
    visibility: public
  - name: web3db
    teams:
      bots: admin
      security-managers: read
      web3db-committers: maintain
    visibility: public
